### PR TITLE
Update to use with Contao 3.5.36 and PHP7.2

### PR DESCRIPTION
**Pull request by silenzium**
Fixed wrong parameter passed to HOOK
Fixed compatibility with PHP>=7
Fixed a PHP warning if styles not set

### CODE REVIEW

**Review by Ruudt — APPROVED** [review]
Thanks

p.s. I will update extension after the weekend as I'm not able to right now.

**Comment by Ruudt** [comment]
I've created a new release. Can you verify this solves the issues you've been having?

**Comment by silenzium** [comment]
Yeah sure I will check it tonight and give you feedback. Thanks @Ruudt

**Comment by silenzium** [comment]
Replaced my fixed version with the current release branch and yep it works great. Thx for the merge!

**Pull request merged**
